### ISSUE TITLE
TODO (Stuff I still need to work on)

### ISSUE THREAD

**Issue by Explosion-Scratch** [Explosion-Scratch/explosion-scratch.github.io#11]
- [x] Add more padding at the bottom of pages (possibly a footer?)
- [x] Make dark theme not reset (Store through ~~cookies~~ localstorage)
- [x] Increase the padding on the dark mode button on mobile
- [x] Increase ```max-width``` to larger.

**Comment by retronbv** [comment]
Use local storage not cookies

**Comment by Explosion-Scratch** [comment]
> Use local storage not cookies

I know. I sort of gave up on that for now lol
